name: Build Releases

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Zig
        env:
          ZIG_VERSION: 0.15.1
        run: |
          mkdir -p $HOME/.local/bin $HOME/.local/zig
          curl "https://ziglang.org/download/${ZIG_VERSION}/zig-x86_64-linux-${ZIG_VERSION}.tar.xz" | tar xJ --strip-components=1 --directory=$HOME/.local/zig
          ln -s $HOME/.local/zig/zig $HOME/.local/bin/zig
          echo "PATH=$PATH:$HOME/.local/bin" >> $GITHUB_ENV

      - name: Build binaries for different platforms
        run: |
          targets=('x86_64-linux' 'aarch64-linux' 'x86_64-macos' 'aarch64-macos' 'x86_64-windows' 'aarch64-windows')
          mkdir bins
          for target in "${targets[@]}"
          do
            zig build -Doptimize=ReleaseSmall -Dtarget=${target}
            mv zig-out/bin/simple-supervisor* ./
            XZ_OPT=-e9 tar caf bins/simple-supervisor.${target}.tar.xz simple-supervisor*
            rm simple-supervisor*
          done

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: bins/*.tar.xz
